### ISSUE TITLE
how can my account be admin account?

### ISSUE THREAD

**Issue by anmol26s** [aymhce/diaspora_ynh#1]
I added myself as admin while web installation. But after installation I have to sign up again and I am not the admin.

How can I add my self admin?

**Comment by aymhce** [comment]
Thanks for your callback.
Actually, if you want to migrate an user to admin role, you have to follow this doc https://wiki.diasporafoundation.org/FAQ_for_pod_maintainers#What_are_roles_and_how_do_I_use_them.3F_.2F_Make_yourself_an_admin

**Comment by anmol26s** [comment]
can you please give command with example for this ?

**Comment by aymhce** [comment]
I don't test it yet but it's like that :

```
sudo su - diaspora
RAILS_ENV=production bundle exec rails console
Role.add_admin User.where(username: "your_username").first.person
```

**Comment by anmol26s** [comment]
That worked 
Thanks!!
