### ISSUE TITLE
App incompatible avec yunohost 2.4

### ISSUE THREAD

**Issue by tomdereub** [aymhce/diaspora_ynh#10]
Salut,
Si j'essaie d'installer diaspora, j'obtiens l'erreur suivante : 
`L'application est incompatible avec votre version de YunoHost : Le paquet de l'application doit être mis à jour pour suivre les changements de YunoHost`
Est-ce que c'est normal ? Est-ce qu'une mise à jour est prévue ?

**Comment by aymhce** [comment]
Bonjour, quelle version Yunohost avez vous précisement svp ?
Pouvez vous exécuter la commande `yunohost --version` svp ?

**Comment by tomdereub** [comment]
yunohost: 2.4.1
yunohost-admin: 2.4.1
moulinette: 2.4.0.1
ssowat: 2.6.0

**Comment by aymhce** [comment]
Effectivement, vous êtes à jour :). Du coup, l'appli est compatible avec YNH 2.4.0. Je n'ai pas encore tester la 2.4.1. Je vais apporter les modifications nécessaires d'ici à 2/3 jours.

**Comment by tomdereub** [comment]
Ok. De toute façon pas d'urgence (en tout cas pour moi), je pars bientôt en vacances donc je testerais ça en septembre.

**Comment by aymhce** [comment]
Bonjour, j'ai installé Yunohost 2.4.1 puis l'application Diaspora :

```
yunohost app install -a "domain=DOMAINEAVECHTTPS&site_public=1" \ 
 https://github.com/aymhce/diaspora_ynh
```

Je n'ai pas rencontré de pb avec la 2.4.1. Pouvez vous re-tester l'installation en ligne de commande svp ?

**Comment by tomdereub** [comment]
C'est bizarre... Avec ta commande, j'ai les erreurs suivantes : 
`Erreur : Valeur invalide pour le paramètre « domain » : Domaine inconnu`
ou
`Erreur : Impossible de récupérer les fichiers sources`
Selon comment je la tape (espace ou pas après le ).
Et si j'essaie de l'installer à partir de l'interface admin dans "installer une application personnalisée", il me dit "Aucun fichier manifest.json"...

**Comment by aymhce** [comment]
dans la commande, il faut que tu remplaces DOMAINEAVECHTTPS par un nom de domaine que tu as déclaré sur ton Yunohost.

**Comment by tomdereub** [comment]
Ok, ça marche !
Est-ce que tu as une idée de pourquoi ça ne marche pas directement via le dépôt community ?

**Comment by aymhce** [comment]
C'est juste, sur le dépôt community, le tag n'est pas à jour.
PR : https://github.com/YunoHost/apps/pull/77

**Comment by aymhce** [comment]
Le dépôt community est à jour.
