### ISSUE TITLE
diaspora  takes defalt page of yunohost login

### ISSUE THREAD

**Issue by anmol26s** [aymhce/diaspora_ynh#2]
Diaspora takes the default page of the yunohost login page.How can I bring back the default page back?

**Comment by aymhce** [comment]
Yes, this is normal. If you want keep Yunohost homepage on your main domain, you have to create a dedicated alias domain for Diaspora (with Yunohost tools ...).
Example :
- main domain : mydomain.com
- alias for diaspora : diaspora.mydomain.com

Command for add domain :
`yunohost domain add diaspora.mydomain.com`

As it is, if you want to return to the YunoHost main page , you will need to uninstall and reinstall Diaspora by indicating the domain : diaspora.mydomain.com

**Comment by anmol26s** [comment]
Can you please configure it to install on mydomain.com/diaspora ?
Installing diaspora on diaspora.mydomain.com gives error:

Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

**Comment by aymhce** [comment]
Sorry, but with original Diaspora app, it's not possible to have a contextpath like "mydomain.com/contextpathfordiaspora". You must have to create a dedicate domain like "subdomainfordiaspora.mydomain.com".
