### ISSUE TITLE
Implement SSO/LDAP

### ISSUE THREAD

**Issue by stevenroose** [aymhce/diaspora_ynh#4]
Just making an issue to track the progress.

Is there any progress yet? :)

**Comment by aymhce** [comment]
Hello, for LDAP connection, it will hard to implement. There is no official plugin for that and contrib plugins are virtually nonexistent. So it will for later...

**Comment by stevenroose** [comment]
@aymhce Is it implemented now, or do you just close it for no reason?

**Comment by aymhce** [comment]
@stevenroose sorry, this feature is disused. Diaspora app remain with that original login pattern , particularly for proposing public account's creation.
