### ISSUE TITLE
What is the license?

### ISSUE THREAD

**Issue by ghost** [aymhce/diaspora_ynh#7]
What is the license? Is it a free/libre one?

**Comment by aymhce** [comment]
It's "libre", yes of course :)
However, I didn't actually said in the manifest.json.

**Comment by ghost** [comment]
Could you specify the license? Some persons may want to do a proprietary version or use patents in their contributions (GNU licences protect against tthat, like [AGPL3](https://www.gnu.org/licenses/agpl-3.0.html) used by YunoHost), so a license to clarify will be usefull.

**Comment by aymhce** [comment]
licence it's free :)
